### ISSUE TITLE
Gets stuck on notarization with `renconstruct build`

### ISSUE THREAD

**Issue by furudean** [kobaltcore/renkit#15]
I have generated certificates using `renotize provision`, but I can't seem to run notarization successfully.

```
> renconstruct build hellogirl/ out
Clearing output directory
Building other packages.
Scanning project files...
[S_API FAIL] SteamAPI_Init() failed; ipcserver init failed .
[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
[S_API] SteamAPI_Init(): Could not determine Steam client install directory.
Scanning Ren'Py files...
Writing the pc zip package. - 2166 of 2166
Writing the pc rpu package. - 2165 of 2165
Writing the mac app-zip package. - 2152 of 2152
Writing the mac rpu package. - 2154 of 2154
Finishing the mac rpu package. - 1995 of 1994All packages have been built.

Due to the presence of permission information, unpacking and repacking the Linux and Macintosh distributions on Windows is not supported.
[Post] Running task: notarize
Unpacking app to "out/hello_girl-1.2.1-mac"
Signing app at "out/hello_girl-1.2.1-mac/hello_girl.app"
Inferred team ID: WRSA45Z5WG
Signing bundle at "out/hello_girl-1.2.1-mac/hello_girl.app"
Notarizing app at "out/hello_girl-1.2.1-mac/hello_girl.app"
Uploading file to notarization service
```

my config looks like this

```toml
[tasks.notarize] # required if matching task is enabled
type = "notarize"
enabled = true
priorities = { post_build = 10 }
on_builds = ["mac"]
bundle_id = "love.maillard.hellogirl"                  # the bundle ID of your came, typically in reverse domain notation
key_file = "certificates/private-key.pem"              # the path to the private key file generated during the provisioning process
cert_file = "certificates/developerID_application.cer" # the path to the Apple-generated certificate file generated during the provisioning process
app_store_key_file = "certificates/app-store-key.json" # the path to the combined App Store key file generated during the provisioning process


[build]
pc = true           # Windows + Linux
win = false         # Windows
linux = false       # Linux
mac = true          # macOS
web = false         # Web
steam = false       # Steam
market = false      # Multiple Markets (i.e. Itch.io)
android_apk = false # Android Universal APK
android_aab = false # Android Play Store Bundle

[options]
clear_output_dir = true # whether to clear the output directory on startup

[renutil]
version = "8.2.0"  # the Ren'Py version to use (required)
registry = "cache" # the directory to store installation files in

```

let me know if i can help debug this in any way!
