### ISSUE TITLE
toml parser barfing on specific syntax

### ISSUE THREAD

**Issue by furudean** [kobaltcore/renkit#24]
here's some valid toml i'm using in `renconstruct.toml`

```toml
[tasks.unzip]
type = "custom"
enabled = true
priorities = { post_build = 20 }
on_builds = ["win", "linux", "mac"]

[tasks.unzip.extract]
"hello_girl-*-win.*" = "steam/win"
"hello_girl-*-mac.*" = "steam/mac"
"hello_girl-*-linux.*" = "steam/linux"
```

however, it seems the parser can't handle this
```
→ renconstruct build hellogirl/ out/
Error: TOML parse error at line 29, column 1
   |
29 | [tasks.unzip]
   | ^^^^^^^^^^^^^
data did not match any variant of untagged enum CustomOptionValue
```

i can't really figure out why, but removing the `[tasks.unzip.extract]` section seems to fix it. any ideas why?

**Comment by kobaltcore** [comment]
Thanks for the report, I'll look into it in the coming days.

**Comment by kobaltcore** [comment]
Ah, this appears to be a misunderstanding in how the config file works: Valid TOML is a superset of valid config data for `renconstruct`. Specifically, there can only be one section per task. What you're trying to specify here is a `.extract` sub-key for the `unzip` task, but the tool has no concept of that. If you merge the two together, it should work and get passed in properly, i.e.
```toml
[tasks.unzip]
type = "custom"
enabled = true
priorities = { post_build = 20 }
on_builds = ["win", "linux", "mac"]
"hello_girl-*-win.*" = "steam/win"
"hello_girl-*-mac.*" = "steam/mac"
"hello_girl-*-linux.*" = "steam/linux"
```
